across:
  development:
    active: true

server:
  error:
    includeStacktrace: ALWAYS
    whitelabel:
      enabled: false
  port: 8080

spring:
  datasource:
    url: "jdbc:h2:./local-data/db/booking-db"
    username: sa

acrossHibernate:
  hibernate-properties:
    hibernate.format_sql: false
    hibernate.use_sql_comments: false
    hibernate.show_sql: false
    hibernate.hbm2ddl.auto: update

adminWebModule:
  title: "AX School: EntityModule"

musicalService:
  url: http://localhost:8099
